version: "2.2"

volumes:
  micro-storage:

services:
  server:
    image: "node:current"
    working_dir: /home/node/app
    volumes:
      - "./server:/home/node/app"
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm start"

  reformer:
    image: "node:current"
    working_dir: /home/node/app
    volumes:
      - "./reformer:/home/node/app"
    command: bash -c "npm i && npm start"

  logger:
    image: "node:current"
    working_dir: /home/node/app
    ports:
      - "4000:4000"
    volumes:
      - "./logger:/home/node/app"
      - "micro-storage:/home/node/volume"
    command: bash -c "npm i && npm start"
